### ISSUE TITLE
HMS used in Docker Demo doesn't support writing tables to S3A

### ISSUE THREAD

**Issue by alberttwong** [onetable-io/onetable#322]
I get .config org.apache.hadoop.fs.s3a.S3AFileSystem not found message. 

```
  hive-metastore:
    container_name: hive-metastore
    hostname: hive-metastore
    image: 'apache/hive:4.0.0-alpha-2'
    ports:
      - '9083:9083' # Metastore Thrift
    environment:
      SERVICE_NAME: metastore
      HIVE_METASTORE_WAREHOUSE_DIR: /home/data
    volumes:
      - ./data:/home/data
```
